[package]
name = "amimono-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ammn"

[dependencies]
cargo = "0.92.0"
clap = "4.5.51"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
