[package]
name = "example-adder"
version = "0.1.0"
edition = "2024"

[dependencies]
amimono = { path = "../amimono" }
env_logger = "0.11.8"
log = "0.4.28"
rand = "0.9.2"
tokio = { version = "1.48.0", features = ["full"] }
